### ISSUE TITLE
Deseable quick starter

### ISSUE THREAD

**Issue by cr0hn** [vrandkode/stuk#1]
Sería deseable que el proyecto tuviera un quick starter para saber cómo poder empezar a usarse

**Comment by guillermijas** [comment]
Quick starter añadido a la parte de autenticación (aplicación RoR)

**Comment by cr0hn** [comment]
Por favor, incluidla en README, es más visible para cualquier usuario

**Comment by guillermijas** [comment]
Actualizado al readme principal
