### ISSUE TITLE
Error de copy&paste?

### ISSUE THREAD

**Issue by cr0hn** [vrandkode/stuk#10]
https://github.com/vrandkode/stuk/blob/274cde6133a81aa8f3dc6728752ad0281d4fed57/supervisor/agent.py#L1

**Comment by vrandkode** [comment]
Efectivamente. Tengo instalado Visual Studio Code con la extensión de acceso remoto, pero no me esta funcionando bien. Asi que por ahora programo directamente usando vim en remoto. :)
