### ISSUE TITLE
Considerar roles y responsabilidades en la documentación

### ISSUE THREAD

**Issue by vaguileradiaz** [vrandkode/stuk#3]
Tener identificados los roles que intervienen y tener claras las funciones de cada uno de ellos. Se podría incluir en la documentación para ayudar a entender el funcionamiento. 

Por ejemplo, a nivel de roles:
- Un perfil de supervisor (administración de perfiles de servicios, alta de usuarios en el servidor final vía SSH, apertura de puertos en los servidores finales, etc.), 
- Un perfil de usuario (inicialmente, se descarga la plantilla de servicio que desea utilizar junto a las características asociadas: puerto, secuencia de port knocking, etc.)
- Un servidor final (monitoriza si se establece la secuencia definida para conectar con el servicio y, en dicho caso, le envía la petición al supervisor para que sea él quien abra el puerto mediante comandos SSH)

**Comment by guillermijas** [comment]
Añadida descripción de los roles de elementos de sistema, parecido a la descripción ofrecida
