### ISSUE TITLE
Claves privadas en Github!

### ISSUE THREAD

**Issue by cr0hn** [vrandkode/stuk#4]
<img width="522" alt="stuk_infrastructure_keys_at_master_ _vrandkode_stuk" src="https://user-images.githubusercontent.com/4076390/49291307-2c522a00-f4aa-11e8-83d3-1b508d826839.png">

**Comment by vrandkode** [comment]
Es una clave privada de uso interno para realizar varias pruebas, no forma parte del mecanismo que envuelve a la solución.
