### ISSUE TITLE
Python environment en github

### ISSUE THREAD

**Issue by cr0hn** [vrandkode/stuk#5]
No debería de estar el entorno virtual de Python en GitHub. Es código innecesario en el repositorio del proyecto.

<img width="650" alt="stuk_client_env_at_master_ _vrandkode_stuk" src="https://user-images.githubusercontent.com/4076390/49291491-ca45f480-f4aa-11e8-9743-25c1fd716923.png">

**Comment by ivanjim** [comment]
Listo, fallo técnico =P. Muchas gracias!
